#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSK2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bska")]
	public partial class LINQtoSQLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGra(Gra instance);
    partial void UpdateGra(Gra instance);
    partial void DeleteGra(Gra instance);
    partial void InsertWypozyczenie(Wypozyczenie instance);
    partial void UpdateWypozyczenie(Wypozyczenie instance);
    partial void DeleteWypozyczenie(Wypozyczenie instance);
    partial void InsertWypo_user(Wypo_user instance);
    partial void UpdateWypo_user(Wypo_user instance);
    partial void DeleteWypo_user(Wypo_user instance);
    partial void InsertFaktura(Faktura instance);
    partial void UpdateFaktura(Faktura instance);
    partial void DeleteFaktura(Faktura instance);
    partial void InsertRola(Rola instance);
    partial void UpdateRola(Rola instance);
    partial void DeleteRola(Rola instance);
    partial void InsertWypo_gra(Wypo_gra instance);
    partial void UpdateWypo_gra(Wypo_gra instance);
    partial void DeleteWypo_gra(Wypo_gra instance);
    partial void InsertUzytkownik(Uzytkownik instance);
    partial void UpdateUzytkownik(Uzytkownik instance);
    partial void DeleteUzytkownik(Uzytkownik instance);
    partial void InsertPoziomUfnosci(PoziomUfnosci instance);
    partial void UpdatePoziomUfnosci(PoziomUfnosci instance);
    partial void DeletePoziomUfnosci(PoziomUfnosci instance);
    #endregion
		
		public LINQtoSQLDataContext() : 
				base(global::BSK2.Properties.Settings.Default.bskaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Gra> Gras
		{
			get
			{
				return this.GetTable<Gra>();
			}
		}
		
		public System.Data.Linq.Table<Wypozyczenie> Wypozyczenies
		{
			get
			{
				return this.GetTable<Wypozyczenie>();
			}
		}
		
		public System.Data.Linq.Table<Wypo_user> Wypo_users
		{
			get
			{
				return this.GetTable<Wypo_user>();
			}
		}
		
		public System.Data.Linq.Table<Faktura> Fakturas
		{
			get
			{
				return this.GetTable<Faktura>();
			}
		}
		
		public System.Data.Linq.Table<Rola> Rolas
		{
			get
			{
				return this.GetTable<Rola>();
			}
		}
		
		public System.Data.Linq.Table<Wypo_gra> Wypo_gras
		{
			get
			{
				return this.GetTable<Wypo_gra>();
			}
		}
		
		public System.Data.Linq.Table<Uzytkownik> Uzytkowniks
		{
			get
			{
				return this.GetTable<Uzytkownik>();
			}
		}
		
		public System.Data.Linq.Table<PoziomUfnosci> PoziomUfnoscis
		{
			get
			{
				return this.GetTable<PoziomUfnosci>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Gra")]
	public partial class Gra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Nazwa;
		
		private string _Opis;
		
		private decimal _Cena_dzien;
		
		private string _Kategoria;
		
		private decimal _Kaucja;
		
		private System.Nullable<int> _Classification;
		
		private EntitySet<Wypo_gra> _Wypo_gras;
		
		private EntityRef<PoziomUfnosci> _PoziomUfnosci;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNazwaChanging(string value);
    partial void OnNazwaChanged();
    partial void OnOpisChanging(string value);
    partial void OnOpisChanged();
    partial void OnCena_dzienChanging(decimal value);
    partial void OnCena_dzienChanged();
    partial void OnKategoriaChanging(string value);
    partial void OnKategoriaChanged();
    partial void OnKaucjaChanging(decimal value);
    partial void OnKaucjaChanged();
    partial void OnClassificationChanging(System.Nullable<int> value);
    partial void OnClassificationChanged();
    #endregion
		
		public Gra()
		{
			this._Wypo_gras = new EntitySet<Wypo_gra>(new Action<Wypo_gra>(this.attach_Wypo_gras), new Action<Wypo_gra>(this.detach_Wypo_gras));
			this._PoziomUfnosci = default(EntityRef<PoziomUfnosci>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nazwa
		{
			get
			{
				return this._Nazwa;
			}
			set
			{
				if ((this._Nazwa != value))
				{
					this.OnNazwaChanging(value);
					this.SendPropertyChanging();
					this._Nazwa = value;
					this.SendPropertyChanged("Nazwa");
					this.OnNazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opis", DbType="VarChar(300)")]
		public string Opis
		{
			get
			{
				return this._Opis;
			}
			set
			{
				if ((this._Opis != value))
				{
					this.OnOpisChanging(value);
					this.SendPropertyChanging();
					this._Opis = value;
					this.SendPropertyChanged("Opis");
					this.OnOpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cena_dzien", DbType="Decimal(18,0) NOT NULL")]
		public decimal Cena_dzien
		{
			get
			{
				return this._Cena_dzien;
			}
			set
			{
				if ((this._Cena_dzien != value))
				{
					this.OnCena_dzienChanging(value);
					this.SendPropertyChanging();
					this._Cena_dzien = value;
					this.SendPropertyChanged("Cena_dzien");
					this.OnCena_dzienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kategoria", DbType="VarChar(30)")]
		public string Kategoria
		{
			get
			{
				return this._Kategoria;
			}
			set
			{
				if ((this._Kategoria != value))
				{
					this.OnKategoriaChanging(value);
					this.SendPropertyChanging();
					this._Kategoria = value;
					this.SendPropertyChanged("Kategoria");
					this.OnKategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kaucja", DbType="Decimal(18,0) NOT NULL")]
		public decimal Kaucja
		{
			get
			{
				return this._Kaucja;
			}
			set
			{
				if ((this._Kaucja != value))
				{
					this.OnKaucjaChanging(value);
					this.SendPropertyChanging();
					this._Kaucja = value;
					this.SendPropertyChanged("Kaucja");
					this.OnKaucjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Classification", DbType="Int")]
		public System.Nullable<int> Classification
		{
			get
			{
				return this._Classification;
			}
			set
			{
				if ((this._Classification != value))
				{
					if (this._PoziomUfnosci.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClassificationChanging(value);
					this.SendPropertyChanging();
					this._Classification = value;
					this.SendPropertyChanged("Classification");
					this.OnClassificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Gra_Wypo_gra", Storage="_Wypo_gras", ThisKey="ID", OtherKey="ID_gry")]
		public EntitySet<Wypo_gra> Wypo_gras
		{
			get
			{
				return this._Wypo_gras;
			}
			set
			{
				this._Wypo_gras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PoziomUfnosci_Gra", Storage="_PoziomUfnosci", ThisKey="Classification", OtherKey="ID", IsForeignKey=true, DeleteRule="SET NULL")]
		public PoziomUfnosci PoziomUfnosci
		{
			get
			{
				return this._PoziomUfnosci.Entity;
			}
			set
			{
				PoziomUfnosci previousValue = this._PoziomUfnosci.Entity;
				if (((previousValue != value) 
							|| (this._PoziomUfnosci.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PoziomUfnosci.Entity = null;
						previousValue.Gras.Remove(this);
					}
					this._PoziomUfnosci.Entity = value;
					if ((value != null))
					{
						value.Gras.Add(this);
						this._Classification = value.ID;
					}
					else
					{
						this._Classification = default(Nullable<int>);
					}
					this.SendPropertyChanged("PoziomUfnosci");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Wypo_gras(Wypo_gra entity)
		{
			this.SendPropertyChanging();
			entity.Gra = this;
		}
		
		private void detach_Wypo_gras(Wypo_gra entity)
		{
			this.SendPropertyChanging();
			entity.Gra = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Wypozyczenie")]
	public partial class Wypozyczenie : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.DateTime _Data_wypozyczenia;
		
		private System.Nullable<System.DateTime> _Data_zwrotu;
		
		private decimal _Cena;
		
		private System.Nullable<decimal> _Kara;
		
		private string _Status_Wypo;
		
		private System.Nullable<int> _ID_Faktury;
		
		private System.Nullable<int> _Classification;
		
		private EntitySet<Wypo_user> _Wypo_users;
		
		private EntitySet<Wypo_gra> _Wypo_gras;
		
		private EntityRef<Faktura> _Faktura;
		
		private EntityRef<PoziomUfnosci> _PoziomUfnosci;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnData_wypozyczeniaChanging(System.DateTime value);
    partial void OnData_wypozyczeniaChanged();
    partial void OnData_zwrotuChanging(System.Nullable<System.DateTime> value);
    partial void OnData_zwrotuChanged();
    partial void OnCenaChanging(decimal value);
    partial void OnCenaChanged();
    partial void OnKaraChanging(System.Nullable<decimal> value);
    partial void OnKaraChanged();
    partial void OnStatus_WypoChanging(string value);
    partial void OnStatus_WypoChanged();
    partial void OnID_FakturyChanging(System.Nullable<int> value);
    partial void OnID_FakturyChanged();
    partial void OnClassificationChanging(System.Nullable<int> value);
    partial void OnClassificationChanged();
    #endregion
		
		public Wypozyczenie()
		{
			this._Wypo_users = new EntitySet<Wypo_user>(new Action<Wypo_user>(this.attach_Wypo_users), new Action<Wypo_user>(this.detach_Wypo_users));
			this._Wypo_gras = new EntitySet<Wypo_gra>(new Action<Wypo_gra>(this.attach_Wypo_gras), new Action<Wypo_gra>(this.detach_Wypo_gras));
			this._Faktura = default(EntityRef<Faktura>);
			this._PoziomUfnosci = default(EntityRef<PoziomUfnosci>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_wypozyczenia", DbType="Date NOT NULL")]
		public System.DateTime Data_wypozyczenia
		{
			get
			{
				return this._Data_wypozyczenia;
			}
			set
			{
				if ((this._Data_wypozyczenia != value))
				{
					this.OnData_wypozyczeniaChanging(value);
					this.SendPropertyChanging();
					this._Data_wypozyczenia = value;
					this.SendPropertyChanged("Data_wypozyczenia");
					this.OnData_wypozyczeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_zwrotu", DbType="Date")]
		public System.Nullable<System.DateTime> Data_zwrotu
		{
			get
			{
				return this._Data_zwrotu;
			}
			set
			{
				if ((this._Data_zwrotu != value))
				{
					this.OnData_zwrotuChanging(value);
					this.SendPropertyChanging();
					this._Data_zwrotu = value;
					this.SendPropertyChanged("Data_zwrotu");
					this.OnData_zwrotuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cena", DbType="Decimal(18,0) NOT NULL")]
		public decimal Cena
		{
			get
			{
				return this._Cena;
			}
			set
			{
				if ((this._Cena != value))
				{
					this.OnCenaChanging(value);
					this.SendPropertyChanging();
					this._Cena = value;
					this.SendPropertyChanged("Cena");
					this.OnCenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kara", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Kara
		{
			get
			{
				return this._Kara;
			}
			set
			{
				if ((this._Kara != value))
				{
					this.OnKaraChanging(value);
					this.SendPropertyChanging();
					this._Kara = value;
					this.SendPropertyChanged("Kara");
					this.OnKaraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status_Wypo", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Status_Wypo
		{
			get
			{
				return this._Status_Wypo;
			}
			set
			{
				if ((this._Status_Wypo != value))
				{
					this.OnStatus_WypoChanging(value);
					this.SendPropertyChanging();
					this._Status_Wypo = value;
					this.SendPropertyChanged("Status_Wypo");
					this.OnStatus_WypoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Faktury", DbType="Int")]
		public System.Nullable<int> ID_Faktury
		{
			get
			{
				return this._ID_Faktury;
			}
			set
			{
				if ((this._ID_Faktury != value))
				{
					if (this._Faktura.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_FakturyChanging(value);
					this.SendPropertyChanging();
					this._ID_Faktury = value;
					this.SendPropertyChanged("ID_Faktury");
					this.OnID_FakturyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Classification", DbType="Int")]
		public System.Nullable<int> Classification
		{
			get
			{
				return this._Classification;
			}
			set
			{
				if ((this._Classification != value))
				{
					if (this._PoziomUfnosci.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClassificationChanging(value);
					this.SendPropertyChanging();
					this._Classification = value;
					this.SendPropertyChanged("Classification");
					this.OnClassificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Wypozyczenie_Wypo_user", Storage="_Wypo_users", ThisKey="ID", OtherKey="ID_wypo")]
		public EntitySet<Wypo_user> Wypo_users
		{
			get
			{
				return this._Wypo_users;
			}
			set
			{
				this._Wypo_users.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Wypozyczenie_Wypo_gra", Storage="_Wypo_gras", ThisKey="ID", OtherKey="ID_wypo")]
		public EntitySet<Wypo_gra> Wypo_gras
		{
			get
			{
				return this._Wypo_gras;
			}
			set
			{
				this._Wypo_gras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Faktura_Wypozyczenie", Storage="_Faktura", ThisKey="ID_Faktury", OtherKey="ID", IsForeignKey=true, DeleteRule="SET NULL")]
		public Faktura Faktura
		{
			get
			{
				return this._Faktura.Entity;
			}
			set
			{
				Faktura previousValue = this._Faktura.Entity;
				if (((previousValue != value) 
							|| (this._Faktura.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Faktura.Entity = null;
						previousValue.Wypozyczenies.Remove(this);
					}
					this._Faktura.Entity = value;
					if ((value != null))
					{
						value.Wypozyczenies.Add(this);
						this._ID_Faktury = value.ID;
					}
					else
					{
						this._ID_Faktury = default(Nullable<int>);
					}
					this.SendPropertyChanged("Faktura");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PoziomUfnosci_Wypozyczenie", Storage="_PoziomUfnosci", ThisKey="Classification", OtherKey="ID", IsForeignKey=true, DeleteRule="SET NULL")]
		public PoziomUfnosci PoziomUfnosci
		{
			get
			{
				return this._PoziomUfnosci.Entity;
			}
			set
			{
				PoziomUfnosci previousValue = this._PoziomUfnosci.Entity;
				if (((previousValue != value) 
							|| (this._PoziomUfnosci.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PoziomUfnosci.Entity = null;
						previousValue.Wypozyczenies.Remove(this);
					}
					this._PoziomUfnosci.Entity = value;
					if ((value != null))
					{
						value.Wypozyczenies.Add(this);
						this._Classification = value.ID;
					}
					else
					{
						this._Classification = default(Nullable<int>);
					}
					this.SendPropertyChanged("PoziomUfnosci");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Wypo_users(Wypo_user entity)
		{
			this.SendPropertyChanging();
			entity.Wypozyczenie = this;
		}
		
		private void detach_Wypo_users(Wypo_user entity)
		{
			this.SendPropertyChanging();
			entity.Wypozyczenie = null;
		}
		
		private void attach_Wypo_gras(Wypo_gra entity)
		{
			this.SendPropertyChanging();
			entity.Wypozyczenie = this;
		}
		
		private void detach_Wypo_gras(Wypo_gra entity)
		{
			this.SendPropertyChanging();
			entity.Wypozyczenie = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Wypo_user")]
	public partial class Wypo_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_user;
		
		private int _ID_wypo;
		
		private System.Nullable<int> _Classification;
		
		private EntityRef<Wypozyczenie> _Wypozyczenie;
		
		private EntityRef<Uzytkownik> _Uzytkownik;
		
		private EntityRef<PoziomUfnosci> _PoziomUfnosci;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_userChanging(int value);
    partial void OnID_userChanged();
    partial void OnID_wypoChanging(int value);
    partial void OnID_wypoChanged();
    partial void OnClassificationChanging(System.Nullable<int> value);
    partial void OnClassificationChanged();
    #endregion
		
		public Wypo_user()
		{
			this._Wypozyczenie = default(EntityRef<Wypozyczenie>);
			this._Uzytkownik = default(EntityRef<Uzytkownik>);
			this._PoziomUfnosci = default(EntityRef<PoziomUfnosci>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_user", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_user
		{
			get
			{
				return this._ID_user;
			}
			set
			{
				if ((this._ID_user != value))
				{
					if (this._Uzytkownik.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_userChanging(value);
					this.SendPropertyChanging();
					this._ID_user = value;
					this.SendPropertyChanged("ID_user");
					this.OnID_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_wypo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_wypo
		{
			get
			{
				return this._ID_wypo;
			}
			set
			{
				if ((this._ID_wypo != value))
				{
					if (this._Wypozyczenie.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_wypoChanging(value);
					this.SendPropertyChanging();
					this._ID_wypo = value;
					this.SendPropertyChanged("ID_wypo");
					this.OnID_wypoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Classification", DbType="Int")]
		public System.Nullable<int> Classification
		{
			get
			{
				return this._Classification;
			}
			set
			{
				if ((this._Classification != value))
				{
					if (this._PoziomUfnosci.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClassificationChanging(value);
					this.SendPropertyChanging();
					this._Classification = value;
					this.SendPropertyChanged("Classification");
					this.OnClassificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Wypozyczenie_Wypo_user", Storage="_Wypozyczenie", ThisKey="ID_wypo", OtherKey="ID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Wypozyczenie Wypozyczenie
		{
			get
			{
				return this._Wypozyczenie.Entity;
			}
			set
			{
				Wypozyczenie previousValue = this._Wypozyczenie.Entity;
				if (((previousValue != value) 
							|| (this._Wypozyczenie.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Wypozyczenie.Entity = null;
						previousValue.Wypo_users.Remove(this);
					}
					this._Wypozyczenie.Entity = value;
					if ((value != null))
					{
						value.Wypo_users.Add(this);
						this._ID_wypo = value.ID;
					}
					else
					{
						this._ID_wypo = default(int);
					}
					this.SendPropertyChanged("Wypozyczenie");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Uzytkownik_Wypo_user", Storage="_Uzytkownik", ThisKey="ID_user", OtherKey="ID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Uzytkownik Uzytkownik
		{
			get
			{
				return this._Uzytkownik.Entity;
			}
			set
			{
				Uzytkownik previousValue = this._Uzytkownik.Entity;
				if (((previousValue != value) 
							|| (this._Uzytkownik.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Uzytkownik.Entity = null;
						previousValue.Wypo_users.Remove(this);
					}
					this._Uzytkownik.Entity = value;
					if ((value != null))
					{
						value.Wypo_users.Add(this);
						this._ID_user = value.ID;
					}
					else
					{
						this._ID_user = default(int);
					}
					this.SendPropertyChanged("Uzytkownik");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PoziomUfnosci_Wypo_user", Storage="_PoziomUfnosci", ThisKey="Classification", OtherKey="ID", IsForeignKey=true, DeleteRule="SET NULL")]
		public PoziomUfnosci PoziomUfnosci
		{
			get
			{
				return this._PoziomUfnosci.Entity;
			}
			set
			{
				PoziomUfnosci previousValue = this._PoziomUfnosci.Entity;
				if (((previousValue != value) 
							|| (this._PoziomUfnosci.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PoziomUfnosci.Entity = null;
						previousValue.Wypo_users.Remove(this);
					}
					this._PoziomUfnosci.Entity = value;
					if ((value != null))
					{
						value.Wypo_users.Add(this);
						this._Classification = value.ID;
					}
					else
					{
						this._Classification = default(Nullable<int>);
					}
					this.SendPropertyChanged("PoziomUfnosci");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Faktura")]
	public partial class Faktura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<System.DateTime> _Data_wystawienia;
		
		private System.Nullable<int> _ID_user;
		
		private System.Nullable<int> _Classification;
		
		private EntitySet<Wypozyczenie> _Wypozyczenies;
		
		private EntityRef<Uzytkownik> _Uzytkownik;
		
		private EntityRef<PoziomUfnosci> _PoziomUfnosci;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnData_wystawieniaChanging(System.Nullable<System.DateTime> value);
    partial void OnData_wystawieniaChanged();
    partial void OnID_userChanging(System.Nullable<int> value);
    partial void OnID_userChanged();
    partial void OnClassificationChanging(System.Nullable<int> value);
    partial void OnClassificationChanged();
    #endregion
		
		public Faktura()
		{
			this._Wypozyczenies = new EntitySet<Wypozyczenie>(new Action<Wypozyczenie>(this.attach_Wypozyczenies), new Action<Wypozyczenie>(this.detach_Wypozyczenies));
			this._Uzytkownik = default(EntityRef<Uzytkownik>);
			this._PoziomUfnosci = default(EntityRef<PoziomUfnosci>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_wystawienia", DbType="Date")]
		public System.Nullable<System.DateTime> Data_wystawienia
		{
			get
			{
				return this._Data_wystawienia;
			}
			set
			{
				if ((this._Data_wystawienia != value))
				{
					this.OnData_wystawieniaChanging(value);
					this.SendPropertyChanging();
					this._Data_wystawienia = value;
					this.SendPropertyChanged("Data_wystawienia");
					this.OnData_wystawieniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_user", DbType="Int")]
		public System.Nullable<int> ID_user
		{
			get
			{
				return this._ID_user;
			}
			set
			{
				if ((this._ID_user != value))
				{
					if (this._Uzytkownik.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_userChanging(value);
					this.SendPropertyChanging();
					this._ID_user = value;
					this.SendPropertyChanged("ID_user");
					this.OnID_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Classification", DbType="Int")]
		public System.Nullable<int> Classification
		{
			get
			{
				return this._Classification;
			}
			set
			{
				if ((this._Classification != value))
				{
					if (this._PoziomUfnosci.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClassificationChanging(value);
					this.SendPropertyChanging();
					this._Classification = value;
					this.SendPropertyChanged("Classification");
					this.OnClassificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Faktura_Wypozyczenie", Storage="_Wypozyczenies", ThisKey="ID", OtherKey="ID_Faktury")]
		public EntitySet<Wypozyczenie> Wypozyczenies
		{
			get
			{
				return this._Wypozyczenies;
			}
			set
			{
				this._Wypozyczenies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Uzytkownik_Faktura", Storage="_Uzytkownik", ThisKey="ID_user", OtherKey="ID", IsForeignKey=true, DeleteRule="SET NULL")]
		public Uzytkownik Uzytkownik
		{
			get
			{
				return this._Uzytkownik.Entity;
			}
			set
			{
				Uzytkownik previousValue = this._Uzytkownik.Entity;
				if (((previousValue != value) 
							|| (this._Uzytkownik.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Uzytkownik.Entity = null;
						previousValue.Fakturas.Remove(this);
					}
					this._Uzytkownik.Entity = value;
					if ((value != null))
					{
						value.Fakturas.Add(this);
						this._ID_user = value.ID;
					}
					else
					{
						this._ID_user = default(Nullable<int>);
					}
					this.SendPropertyChanged("Uzytkownik");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PoziomUfnosci_Faktura", Storage="_PoziomUfnosci", ThisKey="Classification", OtherKey="ID", IsForeignKey=true, DeleteRule="SET NULL")]
		public PoziomUfnosci PoziomUfnosci
		{
			get
			{
				return this._PoziomUfnosci.Entity;
			}
			set
			{
				PoziomUfnosci previousValue = this._PoziomUfnosci.Entity;
				if (((previousValue != value) 
							|| (this._PoziomUfnosci.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PoziomUfnosci.Entity = null;
						previousValue.Fakturas.Remove(this);
					}
					this._PoziomUfnosci.Entity = value;
					if ((value != null))
					{
						value.Fakturas.Add(this);
						this._Classification = value.ID;
					}
					else
					{
						this._Classification = default(Nullable<int>);
					}
					this.SendPropertyChanged("PoziomUfnosci");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Wypozyczenies(Wypozyczenie entity)
		{
			this.SendPropertyChanging();
			entity.Faktura = this;
		}
		
		private void detach_Wypozyczenies(Wypozyczenie entity)
		{
			this.SendPropertyChanging();
			entity.Faktura = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rola")]
	public partial class Rola : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Nazwa;
		
		private System.Nullable<int> _Clearance;
		
		private EntitySet<Uzytkownik> _Uzytkowniks;
		
		private EntityRef<PoziomUfnosci> _PoziomUfnosci;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNazwaChanging(string value);
    partial void OnNazwaChanged();
    partial void OnClearanceChanging(System.Nullable<int> value);
    partial void OnClearanceChanged();
    #endregion
		
		public Rola()
		{
			this._Uzytkowniks = new EntitySet<Uzytkownik>(new Action<Uzytkownik>(this.attach_Uzytkowniks), new Action<Uzytkownik>(this.detach_Uzytkowniks));
			this._PoziomUfnosci = default(EntityRef<PoziomUfnosci>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nazwa
		{
			get
			{
				return this._Nazwa;
			}
			set
			{
				if ((this._Nazwa != value))
				{
					this.OnNazwaChanging(value);
					this.SendPropertyChanging();
					this._Nazwa = value;
					this.SendPropertyChanged("Nazwa");
					this.OnNazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clearance", DbType="Int")]
		public System.Nullable<int> Clearance
		{
			get
			{
				return this._Clearance;
			}
			set
			{
				if ((this._Clearance != value))
				{
					if (this._PoziomUfnosci.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClearanceChanging(value);
					this.SendPropertyChanging();
					this._Clearance = value;
					this.SendPropertyChanged("Clearance");
					this.OnClearanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rola_Uzytkownik", Storage="_Uzytkowniks", ThisKey="ID", OtherKey="ID_roli")]
		public EntitySet<Uzytkownik> Uzytkowniks
		{
			get
			{
				return this._Uzytkowniks;
			}
			set
			{
				this._Uzytkowniks.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PoziomUfnosci_Rola", Storage="_PoziomUfnosci", ThisKey="Clearance", OtherKey="ID", IsForeignKey=true, DeleteRule="SET NULL")]
		public PoziomUfnosci PoziomUfnosci
		{
			get
			{
				return this._PoziomUfnosci.Entity;
			}
			set
			{
				PoziomUfnosci previousValue = this._PoziomUfnosci.Entity;
				if (((previousValue != value) 
							|| (this._PoziomUfnosci.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PoziomUfnosci.Entity = null;
						previousValue.Rolas.Remove(this);
					}
					this._PoziomUfnosci.Entity = value;
					if ((value != null))
					{
						value.Rolas.Add(this);
						this._Clearance = value.ID;
					}
					else
					{
						this._Clearance = default(Nullable<int>);
					}
					this.SendPropertyChanged("PoziomUfnosci");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Uzytkowniks(Uzytkownik entity)
		{
			this.SendPropertyChanging();
			entity.Rola = this;
		}
		
		private void detach_Uzytkowniks(Uzytkownik entity)
		{
			this.SendPropertyChanging();
			entity.Rola = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Wypo_gra")]
	public partial class Wypo_gra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_gry;
		
		private int _ID_wypo;
		
		private System.Nullable<int> _Rabat;
		
		private System.Nullable<int> _Classification;
		
		private EntityRef<Gra> _Gra;
		
		private EntityRef<Wypozyczenie> _Wypozyczenie;
		
		private EntityRef<PoziomUfnosci> _PoziomUfnosci;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_gryChanging(int value);
    partial void OnID_gryChanged();
    partial void OnID_wypoChanging(int value);
    partial void OnID_wypoChanged();
    partial void OnRabatChanging(System.Nullable<int> value);
    partial void OnRabatChanged();
    partial void OnClassificationChanging(System.Nullable<int> value);
    partial void OnClassificationChanged();
    #endregion
		
		public Wypo_gra()
		{
			this._Gra = default(EntityRef<Gra>);
			this._Wypozyczenie = default(EntityRef<Wypozyczenie>);
			this._PoziomUfnosci = default(EntityRef<PoziomUfnosci>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_gry", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_gry
		{
			get
			{
				return this._ID_gry;
			}
			set
			{
				if ((this._ID_gry != value))
				{
					if (this._Gra.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_gryChanging(value);
					this.SendPropertyChanging();
					this._ID_gry = value;
					this.SendPropertyChanged("ID_gry");
					this.OnID_gryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_wypo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_wypo
		{
			get
			{
				return this._ID_wypo;
			}
			set
			{
				if ((this._ID_wypo != value))
				{
					if (this._Wypozyczenie.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_wypoChanging(value);
					this.SendPropertyChanging();
					this._ID_wypo = value;
					this.SendPropertyChanged("ID_wypo");
					this.OnID_wypoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rabat", DbType="Int")]
		public System.Nullable<int> Rabat
		{
			get
			{
				return this._Rabat;
			}
			set
			{
				if ((this._Rabat != value))
				{
					this.OnRabatChanging(value);
					this.SendPropertyChanging();
					this._Rabat = value;
					this.SendPropertyChanged("Rabat");
					this.OnRabatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Classification", DbType="Int")]
		public System.Nullable<int> Classification
		{
			get
			{
				return this._Classification;
			}
			set
			{
				if ((this._Classification != value))
				{
					if (this._PoziomUfnosci.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClassificationChanging(value);
					this.SendPropertyChanging();
					this._Classification = value;
					this.SendPropertyChanged("Classification");
					this.OnClassificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Gra_Wypo_gra", Storage="_Gra", ThisKey="ID_gry", OtherKey="ID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Gra Gra
		{
			get
			{
				return this._Gra.Entity;
			}
			set
			{
				Gra previousValue = this._Gra.Entity;
				if (((previousValue != value) 
							|| (this._Gra.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Gra.Entity = null;
						previousValue.Wypo_gras.Remove(this);
					}
					this._Gra.Entity = value;
					if ((value != null))
					{
						value.Wypo_gras.Add(this);
						this._ID_gry = value.ID;
					}
					else
					{
						this._ID_gry = default(int);
					}
					this.SendPropertyChanged("Gra");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Wypozyczenie_Wypo_gra", Storage="_Wypozyczenie", ThisKey="ID_wypo", OtherKey="ID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Wypozyczenie Wypozyczenie
		{
			get
			{
				return this._Wypozyczenie.Entity;
			}
			set
			{
				Wypozyczenie previousValue = this._Wypozyczenie.Entity;
				if (((previousValue != value) 
							|| (this._Wypozyczenie.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Wypozyczenie.Entity = null;
						previousValue.Wypo_gras.Remove(this);
					}
					this._Wypozyczenie.Entity = value;
					if ((value != null))
					{
						value.Wypo_gras.Add(this);
						this._ID_wypo = value.ID;
					}
					else
					{
						this._ID_wypo = default(int);
					}
					this.SendPropertyChanged("Wypozyczenie");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PoziomUfnosci_Wypo_gra", Storage="_PoziomUfnosci", ThisKey="Classification", OtherKey="ID", IsForeignKey=true, DeleteRule="SET NULL")]
		public PoziomUfnosci PoziomUfnosci
		{
			get
			{
				return this._PoziomUfnosci.Entity;
			}
			set
			{
				PoziomUfnosci previousValue = this._PoziomUfnosci.Entity;
				if (((previousValue != value) 
							|| (this._PoziomUfnosci.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PoziomUfnosci.Entity = null;
						previousValue.Wypo_gras.Remove(this);
					}
					this._PoziomUfnosci.Entity = value;
					if ((value != null))
					{
						value.Wypo_gras.Add(this);
						this._Classification = value.ID;
					}
					else
					{
						this._Classification = default(Nullable<int>);
					}
					this.SendPropertyChanged("PoziomUfnosci");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Uzytkownik")]
	public partial class Uzytkownik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Imie;
		
		private string _Nazwisko;
		
		private string _Nr_telefonu;
		
		private string _User_login;
		
		private string _Haslo;
		
		private System.Nullable<int> _ID_roli;
		
		private System.Nullable<int> _Classification;
		
		private EntitySet<Wypo_user> _Wypo_users;
		
		private EntitySet<Faktura> _Fakturas;
		
		private EntityRef<Rola> _Rola;
		
		private EntityRef<PoziomUfnosci> _PoziomUfnosci;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnImieChanging(string value);
    partial void OnImieChanged();
    partial void OnNazwiskoChanging(string value);
    partial void OnNazwiskoChanged();
    partial void OnNr_telefonuChanging(string value);
    partial void OnNr_telefonuChanged();
    partial void OnUser_loginChanging(string value);
    partial void OnUser_loginChanged();
    partial void OnHasloChanging(string value);
    partial void OnHasloChanged();
    partial void OnID_roliChanging(System.Nullable<int> value);
    partial void OnID_roliChanged();
    partial void OnClassificationChanging(System.Nullable<int> value);
    partial void OnClassificationChanged();
    #endregion
		
		public Uzytkownik()
		{
			this._Wypo_users = new EntitySet<Wypo_user>(new Action<Wypo_user>(this.attach_Wypo_users), new Action<Wypo_user>(this.detach_Wypo_users));
			this._Fakturas = new EntitySet<Faktura>(new Action<Faktura>(this.attach_Fakturas), new Action<Faktura>(this.detach_Fakturas));
			this._Rola = default(EntityRef<Rola>);
			this._PoziomUfnosci = default(EntityRef<PoziomUfnosci>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imie", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Imie
		{
			get
			{
				return this._Imie;
			}
			set
			{
				if ((this._Imie != value))
				{
					this.OnImieChanging(value);
					this.SendPropertyChanging();
					this._Imie = value;
					this.SendPropertyChanged("Imie");
					this.OnImieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwisko", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nazwisko
		{
			get
			{
				return this._Nazwisko;
			}
			set
			{
				if ((this._Nazwisko != value))
				{
					this.OnNazwiskoChanging(value);
					this.SendPropertyChanging();
					this._Nazwisko = value;
					this.SendPropertyChanged("Nazwisko");
					this.OnNazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_telefonu", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string Nr_telefonu
		{
			get
			{
				return this._Nr_telefonu;
			}
			set
			{
				if ((this._Nr_telefonu != value))
				{
					this.OnNr_telefonuChanging(value);
					this.SendPropertyChanging();
					this._Nr_telefonu = value;
					this.SendPropertyChanged("Nr_telefonu");
					this.OnNr_telefonuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_login", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string User_login
		{
			get
			{
				return this._User_login;
			}
			set
			{
				if ((this._User_login != value))
				{
					this.OnUser_loginChanging(value);
					this.SendPropertyChanging();
					this._User_login = value;
					this.SendPropertyChanged("User_login");
					this.OnUser_loginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Haslo", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Haslo
		{
			get
			{
				return this._Haslo;
			}
			set
			{
				if ((this._Haslo != value))
				{
					this.OnHasloChanging(value);
					this.SendPropertyChanging();
					this._Haslo = value;
					this.SendPropertyChanged("Haslo");
					this.OnHasloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_roli", DbType="Int")]
		public System.Nullable<int> ID_roli
		{
			get
			{
				return this._ID_roli;
			}
			set
			{
				if ((this._ID_roli != value))
				{
					if (this._Rola.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_roliChanging(value);
					this.SendPropertyChanging();
					this._ID_roli = value;
					this.SendPropertyChanged("ID_roli");
					this.OnID_roliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Classification", DbType="Int")]
		public System.Nullable<int> Classification
		{
			get
			{
				return this._Classification;
			}
			set
			{
				if ((this._Classification != value))
				{
					if (this._PoziomUfnosci.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnClassificationChanging(value);
					this.SendPropertyChanging();
					this._Classification = value;
					this.SendPropertyChanged("Classification");
					this.OnClassificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Uzytkownik_Wypo_user", Storage="_Wypo_users", ThisKey="ID", OtherKey="ID_user")]
		public EntitySet<Wypo_user> Wypo_users
		{
			get
			{
				return this._Wypo_users;
			}
			set
			{
				this._Wypo_users.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Uzytkownik_Faktura", Storage="_Fakturas", ThisKey="ID", OtherKey="ID_user")]
		public EntitySet<Faktura> Fakturas
		{
			get
			{
				return this._Fakturas;
			}
			set
			{
				this._Fakturas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rola_Uzytkownik", Storage="_Rola", ThisKey="ID_roli", OtherKey="ID", IsForeignKey=true, DeleteRule="SET NULL")]
		public Rola Rola
		{
			get
			{
				return this._Rola.Entity;
			}
			set
			{
				Rola previousValue = this._Rola.Entity;
				if (((previousValue != value) 
							|| (this._Rola.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Rola.Entity = null;
						previousValue.Uzytkowniks.Remove(this);
					}
					this._Rola.Entity = value;
					if ((value != null))
					{
						value.Uzytkowniks.Add(this);
						this._ID_roli = value.ID;
					}
					else
					{
						this._ID_roli = default(Nullable<int>);
					}
					this.SendPropertyChanged("Rola");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PoziomUfnosci_Uzytkownik", Storage="_PoziomUfnosci", ThisKey="Classification", OtherKey="ID", IsForeignKey=true, DeleteRule="SET NULL")]
		public PoziomUfnosci PoziomUfnosci
		{
			get
			{
				return this._PoziomUfnosci.Entity;
			}
			set
			{
				PoziomUfnosci previousValue = this._PoziomUfnosci.Entity;
				if (((previousValue != value) 
							|| (this._PoziomUfnosci.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PoziomUfnosci.Entity = null;
						previousValue.Uzytkowniks.Remove(this);
					}
					this._PoziomUfnosci.Entity = value;
					if ((value != null))
					{
						value.Uzytkowniks.Add(this);
						this._Classification = value.ID;
					}
					else
					{
						this._Classification = default(Nullable<int>);
					}
					this.SendPropertyChanged("PoziomUfnosci");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Wypo_users(Wypo_user entity)
		{
			this.SendPropertyChanging();
			entity.Uzytkownik = this;
		}
		
		private void detach_Wypo_users(Wypo_user entity)
		{
			this.SendPropertyChanging();
			entity.Uzytkownik = null;
		}
		
		private void attach_Fakturas(Faktura entity)
		{
			this.SendPropertyChanging();
			entity.Uzytkownik = this;
		}
		
		private void detach_Fakturas(Faktura entity)
		{
			this.SendPropertyChanging();
			entity.Uzytkownik = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PoziomUfnosci")]
	public partial class PoziomUfnosci : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Nazwa;
		
		private EntitySet<Gra> _Gras;
		
		private EntitySet<Wypozyczenie> _Wypozyczenies;
		
		private EntitySet<Wypo_user> _Wypo_users;
		
		private EntitySet<Faktura> _Fakturas;
		
		private EntitySet<Rola> _Rolas;
		
		private EntitySet<Wypo_gra> _Wypo_gras;
		
		private EntitySet<Uzytkownik> _Uzytkowniks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNazwaChanging(string value);
    partial void OnNazwaChanged();
    #endregion
		
		public PoziomUfnosci()
		{
			this._Gras = new EntitySet<Gra>(new Action<Gra>(this.attach_Gras), new Action<Gra>(this.detach_Gras));
			this._Wypozyczenies = new EntitySet<Wypozyczenie>(new Action<Wypozyczenie>(this.attach_Wypozyczenies), new Action<Wypozyczenie>(this.detach_Wypozyczenies));
			this._Wypo_users = new EntitySet<Wypo_user>(new Action<Wypo_user>(this.attach_Wypo_users), new Action<Wypo_user>(this.detach_Wypo_users));
			this._Fakturas = new EntitySet<Faktura>(new Action<Faktura>(this.attach_Fakturas), new Action<Faktura>(this.detach_Fakturas));
			this._Rolas = new EntitySet<Rola>(new Action<Rola>(this.attach_Rolas), new Action<Rola>(this.detach_Rolas));
			this._Wypo_gras = new EntitySet<Wypo_gra>(new Action<Wypo_gra>(this.attach_Wypo_gras), new Action<Wypo_gra>(this.detach_Wypo_gras));
			this._Uzytkowniks = new EntitySet<Uzytkownik>(new Action<Uzytkownik>(this.attach_Uzytkowniks), new Action<Uzytkownik>(this.detach_Uzytkowniks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nazwa
		{
			get
			{
				return this._Nazwa;
			}
			set
			{
				if ((this._Nazwa != value))
				{
					this.OnNazwaChanging(value);
					this.SendPropertyChanging();
					this._Nazwa = value;
					this.SendPropertyChanged("Nazwa");
					this.OnNazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PoziomUfnosci_Gra", Storage="_Gras", ThisKey="ID", OtherKey="Classification")]
		public EntitySet<Gra> Gras
		{
			get
			{
				return this._Gras;
			}
			set
			{
				this._Gras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PoziomUfnosci_Wypozyczenie", Storage="_Wypozyczenies", ThisKey="ID", OtherKey="Classification")]
		public EntitySet<Wypozyczenie> Wypozyczenies
		{
			get
			{
				return this._Wypozyczenies;
			}
			set
			{
				this._Wypozyczenies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PoziomUfnosci_Wypo_user", Storage="_Wypo_users", ThisKey="ID", OtherKey="Classification")]
		public EntitySet<Wypo_user> Wypo_users
		{
			get
			{
				return this._Wypo_users;
			}
			set
			{
				this._Wypo_users.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PoziomUfnosci_Faktura", Storage="_Fakturas", ThisKey="ID", OtherKey="Classification")]
		public EntitySet<Faktura> Fakturas
		{
			get
			{
				return this._Fakturas;
			}
			set
			{
				this._Fakturas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PoziomUfnosci_Rola", Storage="_Rolas", ThisKey="ID", OtherKey="Clearance")]
		public EntitySet<Rola> Rolas
		{
			get
			{
				return this._Rolas;
			}
			set
			{
				this._Rolas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PoziomUfnosci_Wypo_gra", Storage="_Wypo_gras", ThisKey="ID", OtherKey="Classification")]
		public EntitySet<Wypo_gra> Wypo_gras
		{
			get
			{
				return this._Wypo_gras;
			}
			set
			{
				this._Wypo_gras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PoziomUfnosci_Uzytkownik", Storage="_Uzytkowniks", ThisKey="ID", OtherKey="Classification")]
		public EntitySet<Uzytkownik> Uzytkowniks
		{
			get
			{
				return this._Uzytkowniks;
			}
			set
			{
				this._Uzytkowniks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Gras(Gra entity)
		{
			this.SendPropertyChanging();
			entity.PoziomUfnosci = this;
		}
		
		private void detach_Gras(Gra entity)
		{
			this.SendPropertyChanging();
			entity.PoziomUfnosci = null;
		}
		
		private void attach_Wypozyczenies(Wypozyczenie entity)
		{
			this.SendPropertyChanging();
			entity.PoziomUfnosci = this;
		}
		
		private void detach_Wypozyczenies(Wypozyczenie entity)
		{
			this.SendPropertyChanging();
			entity.PoziomUfnosci = null;
		}
		
		private void attach_Wypo_users(Wypo_user entity)
		{
			this.SendPropertyChanging();
			entity.PoziomUfnosci = this;
		}
		
		private void detach_Wypo_users(Wypo_user entity)
		{
			this.SendPropertyChanging();
			entity.PoziomUfnosci = null;
		}
		
		private void attach_Fakturas(Faktura entity)
		{
			this.SendPropertyChanging();
			entity.PoziomUfnosci = this;
		}
		
		private void detach_Fakturas(Faktura entity)
		{
			this.SendPropertyChanging();
			entity.PoziomUfnosci = null;
		}
		
		private void attach_Rolas(Rola entity)
		{
			this.SendPropertyChanging();
			entity.PoziomUfnosci = this;
		}
		
		private void detach_Rolas(Rola entity)
		{
			this.SendPropertyChanging();
			entity.PoziomUfnosci = null;
		}
		
		private void attach_Wypo_gras(Wypo_gra entity)
		{
			this.SendPropertyChanging();
			entity.PoziomUfnosci = this;
		}
		
		private void detach_Wypo_gras(Wypo_gra entity)
		{
			this.SendPropertyChanging();
			entity.PoziomUfnosci = null;
		}
		
		private void attach_Uzytkowniks(Uzytkownik entity)
		{
			this.SendPropertyChanging();
			entity.PoziomUfnosci = this;
		}
		
		private void detach_Uzytkowniks(Uzytkownik entity)
		{
			this.SendPropertyChanging();
			entity.PoziomUfnosci = null;
		}
	}
}
#pragma warning restore 1591
